version: "3.2"

services:
  db:
    image: customer_care/db
    restart: unless-stopped
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file: &env
      - ../.env
    ports:
      - "127.0.0.1:5430:5432"
    container_name: db

  server:
    image: customer_care/dev/server
    ports:
      - "127.0.0.1:7878:7878"
    env_file:
      *env
    container_name: server

volumes: 
  pgdata:
